"""店铺全功能开关中心 —— BOSS_ALL_IN=True 表示老板试跑全开（不含非视觉感知）"""

BOSS_ALL_IN = True

# ---------- 店铺信息 ----------
STORE_NAME = "我的店铺"
STORE_ID = "store_001"
STORE_AREA_SQM = 120
STORE_CHAIN_ID = "chain_001"

# ---------- 视觉检测基础 ----------
ENABLE_SKIN_DETECT = True
SKIN_OVERLAY_ALPHA = 0.22
SKIN_MIN_RATIO = 0.08
ENABLE_ZONES = True
ENABLE_LINE_CROSSING = True
ENABLE_TRAILS = True
ENABLE_DWELL = True
ENABLE_LOITER_ALERT = True
LOITER_SECONDS = 90
ENABLE_QUEUE_DETECT = True
QUEUE_MIN_PEOPLE = 3
ENABLE_GROUP_DETECT = True
GROUP_DISTANCE = 120
ENABLE_BAG_ASSOCIATION = True
ENABLE_CSV_LOG = True
ENABLE_HEATMAP_SNAPSHOT = True
SNAPSHOT_INTERVAL_SEC = 300
ENABLE_WEB_DASHBOARD = True
WEB_EXPORT_INTERVAL = 2
TRAIL_LENGTH = 40
HEATMAP_DECAY = 0.998
LOG_INTERVAL_SEC = 30

# ---------- 智能分析 ----------
ENABLE_FUNNEL = True
ENABLE_DWELL_TIERS = True
DWELL_TIER_BROWSE = 3
DWELL_TIER_INTEREST = 10
DWELL_TIER_INTENT = 30
ENABLE_CROSS_CAM_REID = True
ENABLE_EVENT_ENGINE = True
ENABLE_DATABASE = True
ENABLE_FORECAST = True
ENABLE_STAFF_DETECT = True
STAFF_DWELL_SECONDS = 300
ENABLE_STAFF_EXCLUDE_COUNT = True
ENABLE_SUSPICIOUS = True
SHELF_IDLE_SECONDS = 45
ENABLE_CROWD_DENSITY = True
ENABLE_SPEED_DETECT = True
SPEED_FAST_PX = 80

# ---------- 行为 / 安全 ----------
ENABLE_FALL_DETECT = True
ENABLE_ZIGZAG_DETECT = True
ZIGZAG_REVERSALS = 4
ENABLE_FAMILY_GROUP = True
FAMILY_DISTANCE = 100
FAMILY_MIN_FRAMES = 15
ENABLE_CONVERSION_TRACK = True
ENABLE_DIRECTION_ARROWS = True
ENABLE_SHELF_ENGAGEMENT = True
ENABLE_DAILY_REPORT = True
DAILY_REPORT_HOUR = 22
ENABLE_WEBHOOK = False
WEBHOOK_URL = ""

# ---------- 非视觉感知（用户要求暂不启用）----------
ENABLE_POS_HOOK = False
ENABLE_DOOR_COUNTER = False
ENABLE_WIFI_PROBE = False
ENABLE_BLE_BEACON = False
ENABLE_RFID_SHELF = False
ENABLE_ESL_MONITOR = False
ENABLE_ENV_SENSORS = False
ENABLE_AUDIO_ANALYSIS = False

# ---------- 视觉进阶（非 YOLO 单一模型）----------
ENABLE_DEEP_REID = True
DEEP_REID_THRESHOLD = 0.62
ENABLE_BEHAVIOR_RECOGNITION = True
ENABLE_OPEN_VOCAB = True
OPEN_VOCAB_MODEL = "yolov8s-worldv2.pt"
OPEN_VOCAB_PROMPTS = ["empty shelf", "product on shelf", "shopping bag", "bottle"]
OPEN_VOCAB_INTERVAL = 60
ENABLE_OCR_SHELF = True
OCR_INTERVAL_SEC = 120
ENABLE_SAM_REFINE = False
SAM_MODEL = "sam_b.pt"
ENABLE_FACE_BLUR = True
FACE_BLUR_STRENGTH = 25

# ---------- 多视角 / 3D 融合 ----------
ENABLE_MULTIVIEW_FUSION = True
MULTIVIEW_GRID_SIZE = 32

# ---------- VLM 多模态 ----------
ENABLE_VLM_ANALYSIS = True
VLM_API_BASE = ""
VLM_API_KEY = ""
VLM_MODEL = "gpt-4o-mini"
VLM_INTERVAL_SEC = 300
ENABLE_VLM_QA = True

# ---------- 事件录像回放 ----------
ENABLE_EVENT_CLIPS = True
CLIP_BUFFER_SEC = 8
CLIP_AFTER_SEC = 12
CLIP_MAX_PER_HOUR = 30

# ---------- 智能层 ----------
ENABLE_ATTRIBUTION = True
ENABLE_ADVANCED_FORECAST = True
ENABLE_DIGITAL_TWIN = True
ENABLE_MULTISTORE = True
ENABLE_ACTIVE_LEARNING = True
ACTIVE_LEARNING_MIN_CONF = 0.45

# ---------- 工程优化 ----------
ENABLE_ANALYSIS_DOWNSCALE = True
ANALYSIS_SCALE = 0.72
ENABLE_PARALLEL_INFERENCE = True
POSE_EVERY_N_FRAMES = 1
INFER_DEVICE = 0

# 轮廓/骨架平滑（减轻闪烁）
OVERLAY_SMOOTH_ALPHA = 0.55
SKELETON_HOLD_FRAMES = 4
SEG_CONF_MIN = 0.38

# ---------- 远程观看（PC 算力 + Mac/Tailscale 浏览器）----------
ENABLE_HEADLESS = True
ENABLE_LIVE_STREAM = True
LIVE_STREAM_JPEG_QUALITY = 72
LIVE_STREAM_FPS = 12
LIVE_STREAM_MAX_WIDTH = 960
DASHBOARD_HOST = "0.0.0.0"
DASHBOARD_PORT = 5050

# 模型
MODEL_SIZE = "l"
